---
apiVersion: v2
description: Jellyfin is a Free Software Media System
name: jellyfin
version: 0.1.0
kubeVersion: ">=1.16.0-0"
keywords:
  - jellyfin
  - plex
  - emby
icon: https://raw.githubusercontent.com/jellyfin/jellyfin-ux/master/branding/SVG/icon-solid-black.svg
sources:
  - https://hub.docker.com/r/jellyfin/jellyfin
  - https://github.com/jellyfin/jellyfin
maintainers:
  - name: sebastian
    email: sebastian@diluz.io
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
