services:
  dyndns:
    image: davd/docker-ddns
    ports:
      - 53:53
      - 53:53/udp
      - 8080:8080
    environment:
      - SHARED_SECRET=${SHARED_SECRET}
      - ZONE=dyndns.diluz.io
      - RECORD_TTL=3600
    restart: always
